Add bazel to python images
Signed-off-by: Prabhu Subramanian <prabhu@appthreat.com>

diff --git a/opensuse/Dockerfile.python39 b/opensuse/Dockerfile.python39
--- a/opensuse/Dockerfile.python39
+++ b/opensuse/Dockerfile.python39
@@ -7,7 +7,21 @@ ENV LC_ALL=en_US.UTF-8 \
     PYTHONPATH=/opt/pypi
 
 ENV PATH=${PATH}:/usr/local/bin:/opt/pypi/bin:
-RUN zypper refresh && zypper --non-interactive update && zypper --non-interactive install -l --no-recommends gcc12 gcc12-c++ gcc12-fortran \
+RUN set -e; \
+    ARCH_NAME="$(rpm --eval '%{_arch}')"; \
+    url=; \
+    case "${ARCH_NAME##*-}" in \
+        'x86_64') \
+            OS_ARCH_SUFFIX=''; \
+            GOBIN_VERSION='amd64'; \
+            ;; \
+        'aarch64') \
+            OS_ARCH_SUFFIX='-aarch64'; \
+            GOBIN_VERSION='arm64'; \
+            ;; \
+        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
+    esac \
+    && zypper refresh && zypper --non-interactive update && zypper --non-interactive install -l --no-recommends gcc12 gcc12-c++ gcc12-fortran \
         python39 python39-devel python39-pip findutils java-22-openjdk-devel \
         bzip2 git-core wget zip unzip make gawk nodejs20 npm20 nodejs20-devel \
     && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 \
@@ -24,6 +38,9 @@ RUN zypper refresh && zypper --non-interactive update && zypper --non-interactiv
     && poetry --version \
     && pipenv --version \
     && gcc --version \
+    && curl -L --output /usr/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-${GOBIN_VERSION} \
+    && chmod +x /usr/bin/bazel \
+    && bazel --version \
     && zypper clean -a
 
 CMD /bin/bash
diff --git a/sle/Dockerfile.node20 b/sle/Dockerfile.node20
--- a/sle/Dockerfile.node20
+++ b/sle/Dockerfile.node20
@@ -9,7 +9,21 @@ ENV JAVA_VERSION=$JAVA_VERSION \
     LANG=en_US.UTF-8 \
     LANGUAGE=en_US.UTF-8
 ENV PATH=${PATH}:${JAVA_HOME}/bin:/usr/local/bin:
-RUN zypper refresh && zypper --non-interactive update && zypper --non-interactive install -l --no-recommends \
+RUN set -e; \
+    ARCH_NAME="$(rpm --eval '%{_arch}')"; \
+    url=; \
+    case "${ARCH_NAME##*-}" in \
+        'x86_64') \
+            OS_ARCH_SUFFIX=''; \
+            GOBIN_VERSION='amd64'; \
+            ;; \
+        'aarch64') \
+            OS_ARCH_SUFFIX='-aarch64'; \
+            GOBIN_VERSION='arm64'; \
+            ;; \
+        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
+    esac \
+    && zypper refresh && zypper --non-interactive update && zypper --non-interactive install -l --no-recommends \
         gcc${GCC_VERSION} gcc${GCC_VERSION}-c++ \
         bzip2 git-core wget zip unzip make gawk python311 python311-pip python311-devel nodejs20-devel \
     && update-alternatives --install /usr/bin/python python /usr/bin/python3.11 10 \
@@ -30,6 +44,9 @@ RUN zypper refresh && zypper --non-interactive update && zypper --non-interactiv
     && node -v \
     && npm -v \
     && python --version \
+    && curl -L --output /usr/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-${GOBIN_VERSION} \
+    && chmod +x /usr/bin/bazel \
+    && bazel --version \
     && zypper clean -a
 
 CMD /bin/bash
diff --git a/sle/Dockerfile.python36 b/sle/Dockerfile.python36
--- a/sle/Dockerfile.python36
+++ b/sle/Dockerfile.python36
@@ -14,7 +14,21 @@ ENV JAVA_VERSION=$JAVA_VERSION \
     LANGUAGE=en_US.UTF-8 \
     NVM_DIR="/root/.nvm"
 ENV PATH=${PATH}:/root/.nvm/versions/node/v${NODE_VERSION}/bin:${JAVA_HOME}/bin:${MAVEN_HOME}/bin:/usr/local/bin:
-RUN zypper refresh && zypper --non-interactive update && zypper --non-interactive install -l --no-recommends gcc${GCC_VERSION} gcc${GCC_VERSION}-c++ gcc${GCC_VERSION}-fortran \
+RUN set -e; \
+    ARCH_NAME="$(rpm --eval '%{_arch}')"; \
+    url=; \
+    case "${ARCH_NAME##*-}" in \
+        'x86_64') \
+            OS_ARCH_SUFFIX=''; \
+            GOBIN_VERSION='amd64'; \
+            ;; \
+        'aarch64') \
+            OS_ARCH_SUFFIX='-aarch64'; \
+            GOBIN_VERSION='arm64'; \
+            ;; \
+        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
+    esac \
+    && zypper refresh && zypper --non-interactive update && zypper --non-interactive install -l --no-recommends gcc${GCC_VERSION} gcc${GCC_VERSION}-c++ gcc${GCC_VERSION}-fortran \
         bzip2 git-core wget zip unzip make gawk \
     && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_VERSION} 10 \
     && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${GCC_VERSION} 10 \
@@ -35,6 +49,9 @@ RUN zypper refresh && zypper --non-interactive update && zypper --non-interactiv
     && node -v \
     && npm -v \
     && gcc --version \
+    && curl -L --output /usr/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-${GOBIN_VERSION} \
+    && chmod +x /usr/bin/bazel \
+    && bazel --version \
     && zypper clean -a
 
 CMD /bin/bash
